### PR TITLE
French translation update

### PR DESCRIPTION
**Pull request by Ronkhar**
Moved 6 files to "old" subfolder (to keep in line with english)
Translated the new files (shinybob)
Copied the new strings added by bob and translated them
Removed obsolete strings
Updated the strings for inserters and belts (following bob update to ENTITY method)
Changed the end of line format from LF to CRLF (same as english cfg files)
Corrected typos in a string about gemstones

### CODE REVIEW

**Review by Firerazer — COMMENTED** [review]
Missing in bobplates the last changes (adding "Engrenage, Billes et Roulements" in cobalt steel around lines 73-85

**Comment by Ronkhar** [comment]
@Firerazer: thanks :)
I downloaded the new english file and uploaded the new version.

**Review by Firerazer — APPROVED** [review]
Nice work :) even if upload the entire file instead of copy/paste string make it hard to review!

**Comment by Ronkhar** [comment]
It should be a one-time issue.
It was caused by the change from lf to crlf, which applies to every line, making the diff view mostly unreadable.

**Pull request merged**
